[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#fbf1c7"
info_bg = "#83a598"
info_fg = "#3c3836"
good_bg = "#b8bb26"
good_fg = "#3c3836"
critical_bg = "#fb4934"
critical_fg = "#3c3836"
warning_fg = "#3c3836"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = "taskwarrior_active"
interval = 10

[[block]]
block = "sound"
driver = "auto"

[[block]]
block = "uptime"

[[block]]
block = "net"
device = "wlan0"
ssid = true
ip = true
speed_down = false
graph_up = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "net"
device = "eth0"
ssid = true
ip = true
speed_down = false
graph_up = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MAm} MB"
clickable = false
warning_mem = 70
critical_mem = 85

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
good = 30
idle = 50
info = 70
warning = 80

[[block]]
block = "load"
interval = 1
format = "{15m} {5m} {1m}"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %-d %b %R"
