[theme]
name = "gruvbox-dark"
[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#fbf1c7"
info_bg = "#83a598"
info_fg = "#3c3836"
good_bg = "#b8bb26"
good_fg = "#3c3836"
critical_bg = "#fb4934"
critical_fg = "#3c3836"
warning_fg = "#3c3836"

[icons]
name = "awesome"

[[block]]
block = "custom"
command = "taskwarrior_active"
interval = 10

[[block]]
block = "custom"
command = "timelogger statusbar"
interval = 10

[[block]]
block = "custom"
command = "statusd-weather Tbilisi"
interval = 60

[[block]]
block = "sound"
driver = "alsa"

[[block]]
block = "maildir"
interval = 60
inboxes = ["/home/krsh/Mail/kr3ssh@gmail.com/INBOX", "/home/krsh/Mail/kr3ssh@pm.me/INBOX", "/home/krsh/Mail/sergey@1158.studio/INBOX", "/home/krsh/Mail/sergey@aww.cloud/INBOX"]
threshold_warning = 1
threshold_critical = 5

# [[block]]
# block = "net"
# device = "wlp3s0"
# ssid = true
# ip = true
# speed_down = false
# graph_up = false
# speed_up = false
# speed_down = false
# interval = 5

[[block]]
block = "net"
device = "eth0"
ssid = true
ip = true
speed_down = false
graph_up = false
speed_up = false
speed_down = false
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{MAg} GB"
clickable = false
warning_mem = 60
critical_mem = 70

[[block]]
block = "cpu"
interval = 1
frequency = true

[[block]]
block = "temperature"
collapsed = true
interval = 10
format = "{min}° min, {max}° max, {average}° avg"
good = 45
idle = 60
info = 75
warning = 84

[[block]]
block = "load"
interval = 1
format = "{15m} {5m} {1m}"

# [[block]]
# block = "battery"
# interval = 10
# format = "{percentage}% {time}"

[[block]]
block = "custom"
command = "statusd-utctime"
interval = 60

[[block]]
block = "time"
interval = 60
format = "%a %-d %b %R"
